### ISSUE TITLE
Not showing results in Macos Sonoma

### ISSUE THREAD

**Issue by vaibhavsingh97** [caleb531/open-conference-url#25]
## Steps to Reproduce
1. Upgrade to Macos Sanoma public beta
2. Update XCode, and command lines to beta
3. Tried to use `conf` in the alfred

## Steps to debug
The issue is with the Apple script, as it appears to be malfunctioning in the updated macOS version.
I attempted to execute the command but encountered a "seg fault" error.
```sh
osascript /Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/get-calendar-events.applescript
[1]    86120 segmentation fault  osascript
```

### Log from Alfred Debugger
```sh
[13:08:43.739] Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074%3EAD06006F-71F6-4731-9942-D0697E95329A)] Queuing argument '(null)'
[13:08:44.256] Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074%3EAD06006F-71F6-4731-9942-D0697E95329A)] Script with argv '(null)' finished
[13:08:44.262] ERROR: Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074%3EAD06006F-71F6-4731-9942-D0697E95329A)] Code 1: Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/list_events.py", line 157, in <module>
    main()
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/list_events.py", line 114, in main
    all_events = get_events_today_with_conference_urls()
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/list_events.py", line 38, in get_events_today_with_conference_urls
    return [event for event in get_events_today() if event.conference_url]
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/list_events.py", line 31, in get_events_today
    event_dicts = get_event_dicts()
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/list_events.py", line 24, in get_event_dicts
    return calendar.get_event_dicts(prefs['calendar_names'])
  File "/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/calendar.py", line 25, in get_event_dicts
    return json.loads(subprocess.check_output([
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['osascript', '/Users/vaibhavsingh/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.803C1F13-CB40-4CAB-87F7-E842DC56A074/ocu/get-calendar-events.applescript']' died with <Signals.SIGSEGV: 11>.
xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates
```

**Comment by caleb531** [comment]
@vaibhavsingh97 Because macOS Sonoma is still in beta, we should not expect that everything will work properly. It's very possible this may still be an issue when it's officially released, but until then, I do not plan to test this workflow against the betas.

However, you may wish to try the icalBuddy integration in [the latest v7 of the workflow](https://github.com/caleb531/open-conference-url/tree/v7). It bypasses AppleScript entirely to fetch event data, and assuming icalBuddy still works under macOS Sonoma currently, then you should be good to go. Just remember to enable the "Use icalBuddy" checkbox in the workflow configuration.

<img width="509" alt="5c471437-40fa-44ae-8b73-ad24194da279" src="https://github.com/caleb531/open-conference-url/assets/872474/be9b7438-1991-473b-8a8e-ef46c3023f17">

**Comment by nklmilojevic** [comment]
I just installed RC of Sonoma (which will be final), and it still happens there. I guess it will need some update once you have time to test it on new OS :)

**Comment by caleb531** [comment]
@nklmilojevic I generally only test new macOS releases when they are officially released as stable. But since this particular GitHub issue was created, I have released v7 of the workflow. So I would highly encourage you to try out the icalBuddy integration, which not only bypasses AppleScript, but is actually more performant than the AppleScript. [See release notes for instructions](https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0).

Anyway, I recommend you give it a try, and let me know how it works on macOS Sonoma.

**Comment by nklmilojevic** [comment]
Hey @caleb531, of course! Didn't mean you should test it right away, just confirming that the bug is still on RC which will highly be the final version.

I confirm that it works properly with ical-buddy and seems faster as well. Thanks!

**Comment by caleb531** [comment]
@vaibhavsingh97 @nklmilojevic I am pleased to report that I have identified the root cause of the AppleScript Segmentation Fault error, and have published a fix in v7.1.0:

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.0

Therefore, closing this issue. But will be happy to reopen if anyone is still experiencing issues on macOS Sonoma.
