### ISSUE TITLE
ValueError: time data 'SingaporeT00:00' does not match format '%Y-%m-%dT%H:%M'

### ISSUE THREAD

**Issue by averkiev** [caleb531/open-conference-url#26]
Hi,
the plugin used to work last week (macOS Sonoma RC2), but today, it started showing an error. The error stack track is below:
`[10:25:18.321] Logging Started...
[10:25:22.237] Open Conference URL[Script Filter] Queuing argument '(null)'
[10:25:22.518] Open Conference URL[Script Filter] Script with argv '(null)' finished
[10:25:22.524] ERROR: Open Conference URL[Script Filter] Code 1: Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 218, in <module>
    main()
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 164, in main
    all_events = get_events_today_with_conference_urls()
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 32, in get_events_today_with_conference_urls
    return [event for event in get_events_today() if event.conference_url]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 27, in get_events_today
    return [Event(event_dict) for event_dict in event_dicts]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 27, in <listcomp>
    return [Event(event_dict) for event_dict in event_dicts]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/event.py", line 33, in __init__
    self.start_datetime = self.parse_datetime(event_dict["startDate"])
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/event.py", line 96, in parse_datetime
    return datetime.strptime(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'SingaporeT00:00' does not match format '%Y-%m-%dT%H:%M'
xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates
[10:25:25.094] Logging Stopped.`

**Comment by AnilRh** [comment]
Same here, the error I see is:
raise ValueError("time data %r does not match format %r" %
ValueError: time data 'T' does not match format '%Y-%m-%dT%H:%M'

What's strange is that the Worflow broke when I updated to Sonoma. I then updated to the latest version of the workflow and enabled iCalBuddy and it started working again. A day later it broke.

A quick attempt to debug revealed one of the events on a calendar was breaking it. Oddly I didn't have this calendar in my calendar list in the configuration. The calendar data that breaks it is:

{'title': 'Alg.ProportionsAssignment [Hansen - Math 1 - 23-24]', 'startDate': 'T', 'endDate': 'T', 'isAllDay': 'false', 'location': '', 'notes': 'stuff'}

In my calendar app this appears as an 8am EDT - 8am EDT entry.

**Comment by AnilRh** [comment]
For now I just modified event.py with a really bad hack:
```
    def parse_datetime(self, raw_datetime: str) -> datetime:
        # Handle events with specific start time
        if raw_datetime == "T":
          raw_datetime = "2000-01-01T00:00" # Dumb hack

```

**Comment by caleb531** [comment]
@AnilRh Yeah, I'm not sure that's the right workaround. I'm still trying to understand what kinds of calendar events trigger this behavior. It feels like the event data is malformed, or perhaps icalBuddy is just not displaying it in the way that I expect.

If you run icalBuddy directly in the Terminal (via the following command), can you please post or email me the output? Feel free to obscure personal/private information:

```sh
icalBuddy --dateFormat '%Y-%m-%d' --noRelativeDates --timeFormat '%H:%M' --noCalendarNames --includeEventProps title,datetime --propertyOrder title,datetime eventsToday+0
```

**Comment by caleb531** [comment]
@averkiev @AnilRh Okay, I've pushed out a beta bugfix release that makes the icalBuddy integration honor the "Calendars" setting. Please also try that out and see if it helps.

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.1-beta.1

**Comment by averkiev** [comment]
@caleb531 , I am still seeing an error with the 7.1.1

[11:42:21.828] ERROR: Open Conference URL[Script Filter] Code 1: Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 218, in <module>
    main()
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 164, in main
    all_events = get_events_today_with_conference_urls()
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 32, in get_events_today_with_conference_urls
    return [event for event in get_events_today() if event.conference_url]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 27, in get_events_today
    return [Event(event_dict) for event_dict in event_dicts]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/list_events.py", line 27, in <listcomp>
    return [Event(event_dict) for event_dict in event_dicts]
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/event.py", line 33, in __init__
    self.start_datetime = self.parse_datetime(event_dict["startDate"])
  File "/Users/yury/Library/Mobile Documents/com~apple~CloudDocs/App Data/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/event.py", line 96, in parse_datetime
    return datetime.strptime(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '528833T00:00' does not match format '%Y-%m-%dT%H:%M'

**Comment by caleb531** [comment]
@averkiev Yeah, just to clarify, v7.1.1 would only fix the problem if the following two conditions are true in your case:

1. You've specified the "Calendars" setting with a non-empty value (i.e. you're specifying specific calendars to pull event data from, rather than all calendars)
2. The offending events are coming from a calendar not among the calendars that you've specified in the "Calendars" setting

**Comment by averkiev** [comment]
@caleb531 , in my case the Calendars setting is empty (meaning fetch from all the calendars).

**Comment by caleb531** [comment]
@averkiev I figured as much. Can you please try running the following in the Terminal and posting or emailing me the output? Again, feel free to obscure personal/private information:

```sh
icalBuddy --dateFormat '%Y-%m-%d' --noRelativeDates --timeFormat '%H:%M' --noCalendarNames --includeEventProps title,datetime --propertyOrder title,datetime eventsToday+0
```

I know we're trying all sorts of things here, so thanks for your patience so far in bearing with me while I try to understand what's going on.

**Comment by averkiev** [comment]
@caleb531 
`• Event 111
    2023-09-28 at 08:30 - 09:00
• Event 111
    2023-09-28 at 10:00 - 10:45
• Event 111
    2023-09-28 at 12:00 - 12:30
• Event 111
    2023-09-28 at 15:00 - 16:00
• Event 111
    2023-09-28 at 15:30 - 16:00
• Event 111
    2023-09-28 at 16:00 - 16:30
• Event 111
    2023-09-28 at 16:30 - 17:00
• Event 111
    2023-09-28 at 17:00 - 17:30
• Event 111
    2023-09-28 at 17:30 - 18:00
• Dinner 🍽
    2023-09-28 at 18:00 - 18:30
• Event 111
    2023-09-28 at 18:30 - 19:00
• Event 111
    2023-09-28 at 19:30 - 20:00
• Event 111
    2023-09-28 at 20:00 - 21:00
• Event 111
    2023-09-28 at 21:00 - 21:30
• Event 111
    2023-09-28 at 22:30 - 23:00
• Event 111
    2023-09-28 at 23:00 - 2023-09-29 at 00:00`

**Comment by caleb531** [comment]
@averkiev Interesting. Well, I think I've found a lead; it seems like the issue could very well be related to all-day events, and perhaps with the one of the regexes being too loose in `ocu/calendars/icalbuddy_calendar.py` (line 90, specifically).

I will start playing around with this tomorrow. First, it's time for bed myself 😅. But I am still determined to get to the bottom of this.

**Comment by AnilRh** [comment]
Thanks @caleb531 

The new version worked well for me, now pulling only my Google Calendar instead of also pulling some subscribed calendars from my Kids school. It's the subscribed calendars that were causing the issue.

Looking at yesterday's events with the command you suggested some examples are:

• Math 1 Daily Math #12 [Hansen - NC Math 1 - 23-24]
• Vocabulary 9/25 [Weldon - SCIENCE-GRADE 7 - S1]
    04:00
• Alg.ProportionsAssignment [Hansen - Math 1 - 23-24] (Canvas)
    08:00

So there are a number of events that have a single time, not a start/end time.

**Comment by caleb531** [comment]
@AnilRh @averkiev Okay, so after some digging, I've discovered that icalBuddy will output only a single time (instead of start+end time) when both times are the same value (effectively creating a zero-duration event).

I've just published v7.1.1-beta.2 with some substantial updates to the parsing logic to better handle this. It should also gracefully ignore events that are unable to be parsed. Please give it a try and let me know how it works!
https://github.com/caleb531/open-conference-url/releases/tag/v7.1.1-beta.2

**Comment by AnilRh** [comment]
Wow that was quick @caleb531, thanks! I removed my calendar filter with the new version and it appears to be working!

**Comment by caleb531** [comment]
Wonderful!

@averkiev, can you please confirm if beta 2 works any better for you?
https://github.com/caleb531/open-conference-url/releases/tag/v7.1.1-beta.2

**Comment by averkiev** [comment]
@caleb531 works for me. Thanks.

**Comment by caleb531** [comment]
Excellent! With that, I have just published the stable v7.1.1 release, and will close this issue now that the issue's resolved for you both.

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.1
